### ISSUE TITLE
Page o' links

### ISSUE THREAD

**Issue by Dizolivemint** [VueSD/website#1]
### A static page of resources.

For example, urls for building a Vue web application such as documentation and cheat sheets for design, styling. Anything and everything Vue related.

An object array could be stored in a separate json or xml file for easy updating and include properties like the following:
* URL
* Short Description
* Category and/or tags

**Comment by Stegosource** [comment]
I like this idea. We can create a markdown or json file for collecting recommended resources.

**Comment by Dizolivemint** [comment]
Never thought about using markdown or how that would work. It would be easier to maintain and look nice on github.

**Comment by Stegosource** [comment]
Yeah, as we get more feature requirements and content, we'll want to look into scalable ways to add it all. Markdown is pretty cool for devs to work on and Vue has some md parsers available that we could leverage.
